import type { ResponseEscalaSubstituicaoDto } from './escala-substituicao.response';
import type { ResponseEscalaDto } from './escala.response';
import { ResponseEventoDto } from '../Evento/evento.response';
import { ResponseMinisterioVoluntarioDto } from '../MinisterioVoluntario/ministerio-voluntario.response';
import { ResponseMinisterioFuncaoDto } from '../MinisterioFuncao/ministerio-funcao.response';
import { EscalaItemStatusEnum } from '../../enums/Escala/escala-item-status.enum';
import { ResponseVoluntarioDto } from '../Voluntario/voluntario.response';

export type ResponseEscalaItemDto = {
  id: string;
  createdAt: string;
  updatedAt: string;
  escalaId: string;
  escala?: ResponseEscalaDto;
  eventoId: string;
  evento?: ResponseEventoDto;
  dataOcorrencia: string;
  dataHoraInicioOcorrencia?: string | null;
  dataHoraTerminoOcorrencia?: string | null;
  localOcorrencia?: string | null;
  voluntarioId?: string;
  voluntario?: ResponseMinisterioVoluntarioDto;
  funcaoId?: string;
  funcao?: ResponseMinisterioFuncaoDto;
  nomeAvulso?: string | null;
  status: EscalaItemStatusEnum;
  substituicaoId?: string;
  substituicao?: ResponseEscalaSubstituicaoDto;
  horarioEnsaio?: string;
  responsavelSetlistVoluntarioId?: string;
  responsavelSetlistVoluntario?: ResponseVoluntarioDto | null;
};
