import { RecorrenciaDiaSemanaEnum } from '../../enums/Evento/recorrencia-dia-semana.enum';
import { RecorrenciaSemanaMesEnum } from '../../enums/Evento/recorrencia-semana-mes.enum';
import { RecorrenciaEnum } from '../../enums/Evento/recorrencia.enum';
import { TemplatePadraoOrigemEnum } from '../../enums/Evento/template-padrao-origem.enum';
import { ResponseEscalaTemplateDto } from '../EscalaTemplate/escala-template.response';
import { ResponseVoluntarioDto } from '../Voluntario/voluntario.response';
import { ResponseEventoDto } from './evento.response';
import { ResponseEventoSetlistItemDto } from './evento-setlist-item.response';

export type ResponseEventoOcorrenciaDto = {
  id: string;
  nome: string;
  descricao?: string;
  local?: string;
  cor: string;
  recorrencia: RecorrenciaEnum;
  recorrenciaSemanaDias?: RecorrenciaDiaSemanaEnum[];
  recorrenciaSemanasMes?: RecorrenciaSemanaMesEnum[];
  recorrenciaACadaMeses?: number;
  dataOcorrencia: string;
  dataInicio?: string;
  dataTermino?: string | null;
  dadosOcorrenciaOrigem?: TemplatePadraoOrigemEnum;
  eventoId: string;
  evento?: ResponseEventoDto;
  templatePadraoId?: string;
  templatePadrao?: ResponseEscalaTemplateDto;
  templatePadraoOrigem?: TemplatePadraoOrigemEnum;
  horarioEnsaio?: string;
  horarioEnsaioOrigem?: TemplatePadraoOrigemEnum;
  responsavelSetlistVoluntarioId?: string | null;
  responsavelSetlistVoluntario?: ResponseVoluntarioDto | null;
  responsavelSetlistOrigem?: TemplatePadraoOrigemEnum | null;
  setlistResumo?: ResponseEventoSetlistItemDto[];
  cancelada?: boolean;
  canceladaEm?: string | null;
};
