import { DropDownItemProps } from '../../components/fields/FancyDropDownItem';

export const UF_LIST: DropDownItemProps<string>[] = [
  { title: 'Acre - AC', value: 'AC' },
  { title: 'Alagoas - AL', value: 'AL' },
  { title: 'Amapá - AP', value: 'AP' },
  { title: 'Amazonas - AM', value: 'AM' },
  { title: 'Bahia - BA', value: 'BA' },
  { title: 'Ceará - CE', value: 'CE' },
  { title: 'Distrito Federal - DF', value: 'DF' },
  { title: 'Espírito Santo - ES', value: 'ES' },
  { title: 'Goiás - GO', value: 'GO' },
  { title: 'Maranhão - MA', value: 'MA' },
  { title: 'Mato Grosso - MT', value: 'MT' },
  { title: 'Mato Grosso do Sul - MS', value: 'MS' },
  { title: 'Minas Gerais - MG', value: 'MG' },
  { title: 'Pará - PA', value: 'PA' },
  { title: 'Paraíba - PB', value: 'PB' },
  { title: 'Paraná - PR', value: 'PR' },
  { title: 'Pernambuco - PE', value: 'PE' },
  { title: 'Piauí - PI', value: 'PI' },
  { title: 'Rio de Janeiro - RJ', value: 'RJ' },
  { title: 'Rio Grande do Norte - RN', value: 'RN' },
  { title: 'Rio Grande do Sul - RS', value: 'RS' },
  { title: 'Rondônia - RO', value: 'RO' },
  { title: 'Roraima - RR', value: 'RR' },
  { title: 'Santa Catarina - SC', value: 'SC' },
  { title: 'São Paulo - SP', value: 'SP' },
  { title: 'Sergipe - SE', value: 'SE' },
  { title: 'Tocantins - TO', value: 'TO' },
];
